### ISSUE TITLE
why write your own userstyle "standard"?

### ISSUE THREAD

**Issue by relative2** [Muirey03/Nebula#1]
there's already a well established one: https://github.com/openstyles/stylus/wiki/Usercss

you can define the nebula colors as css vars and refer to them using `var`

**Comment by relative2** [comment]
Yes, close it without reasoning why you made a new standard for no reason 👍

**Comment by Muirey03** [comment]
The reason we don’t use that standard is because we do not support all of the options in the standard. It made much more sense to just create 3 different values to use just for Nebula as Nebula only offers very limited stylesheet customisation support.
